<? // application/views/scripts/error/error.phtml ?>

<h1><?=$this->translate('An error occurred!')?></h1> 
<h2><?= $this->message ?></h2> 

<? if ('development' == $this->env): ?> 
    <h3>Error information:</h3> 
    <p> 
        <b>Message:</b> <?= $this->exception->getMessage() ?> 
    </p> 

    <!-- <h3>Stack trace:</h3> 
    <pre><?= $this->exception->getTraceAsString() ?></pre> 

    <h3>Request Parameters:</h3> 
    <pre><? var_dump($this->request->getParams()) ?></pre>  -->
<? endif ?>
